### ISSUE TITLE
Use Case 4 Data Flow

### ISSUE THREAD

**Issue by ppeters0502** [sanjar91/Fantastic-Four#11]
This use case was using authentication, where the broker admin or system administrator uploads the file with usernames and passwords to the broker in order to require usernames and passwords for the topics that are published to. I think if I remember right, our misuse case for this was a bad actor modifying the permissions of the file to add, remove or steal credentials from the credentials list.

**Comment by Emily08** [comment]
@ppeters0502 yes, I think we did discuss false authentication for the misuse case

**Comment by ppeters0502** [comment]
[gram for use case 4](https://www.lucidchart.com/invitations/accept/05052dec-098a-41ce-8c7f-76c6e6e23fd1)
I couldn't remember what we agreed on as the misuse action for false authentication, modifying the permissions of the file or spoofing a fake file. I put both as possible actions on this one, we can either keep them both in or take out whichever one is unnecessary. Let me know what you think!
