### ISSUE TITLE
DFD for Broker Admin

### ISSUE THREAD

**Issue by sanjar91** [sanjar91/Fantastic-Four#23]
Reading the use case from Requirement document. Draw a DFD for Broker Admin

**Comment by sanjar91** [comment]
![img_2222](https://user-images.githubusercontent.com/42626731/48038082-ba015a80-e134-11e8-96fb-babe987ea029.png)

**Comment by sanjar91** [comment]
![screen shot 2018-11-05 at 19 55 51](https://user-images.githubusercontent.com/42626731/48038120-dac9b000-e134-11e8-804c-7b2d23dae914.png)

**Comment by ppeters0502** [comment]
Diagram uploaded and complete. Closing on Sanjar's behalf
