### ISSUE TITLE
Find an automated code review software for C

### ISSUE THREAD

**Issue by sanjar91** [sanjar91/Fantastic-Four#33]
Currently looking at Collaborator by Smartbear.

**Comment by sanjar91** [comment]
https://app.codacy.com/project/sanjar91/mosquitto/dashboard

**Comment by ppeters0502** [comment]
Document for Brain Dump:
https://docs.google.com/document/d/1kEDZEWBiBlZbkUXA5zRW_Y3t9WhNftFsHD8szZgFY5E/edit?usp=sharing

**Comment by ppeters0502** [comment]
Closing issue, we're using Codacy, Visual Code Grepper, SonarCloud, Collaborator
