### ISSUE TITLE
Use Case 1 Dataflow

### ISSUE THREAD

**Issue by neil-unomaha** [sanjar91/Fantastic-Four#5]
0) Make sure you have a back story. Where is this system being used? What is its criticality? Who are the stakeholders?

1) Identify five essential dataflows of your project
Ideally, these need to be spread across different external interactors (humans or systems) of your software. Once different external interactors have been identified, the use cases can focus on the most sensitive features used by the external interactor.

2) Identify threat actors (Misusers)
The misusers should be contextualized in your environment of operation and relevant to the dataflows identified above. Use names that help the reader understand their motives, resources, attack of choice, and available access to the system to carry out their attack.

3) Divide up the tasks while you are at it. Assignment Planning.

**Comment by neil-unomaha** [comment]
Discussion of use cases during class.  Draft of Use cases

![use_case_draft](https://user-images.githubusercontent.com/38234505/45935237-fefb7400-bf6e-11e8-9d72-489a8559cfd7.jpeg)

**Comment by neil-unomaha** [comment]
Use Case One on Dry Erase Board.

![use_case_1](https://user-images.githubusercontent.com/38234505/45935286-a7a9d380-bf6f-11e8-9181-f7783414cbe7.jpeg)

**Comment by Emily08** [comment]
Looks ready for Lucidchart!

**Comment by Emily08** [comment]
Neil, is that "includes" between publish order and unpublish order?

**Comment by neil-unomaha** [comment]
@Emily08 yes it is. But now that I look at this I think the directions of the dependencies are incorrect.  

The dependencies should always point towards the use case that should have happened first.  It should point towards the use case that "this" use case "depends" on happening initially.  I'll be working on it tonight in LucidChart and will post it here.

**Comment by neil-unomaha** [comment]
@Emily08 
[Here is what I'm thinking](https://www.lucidchart.com/invitations/accept/8a4af98b-aca3-490d-a449-82ac7ae22337)

**Comment by ppeters0502** [comment]
@Emily08  on that chart, should the misuse case threaten Publish Order, or modify order log? I wasn't sure if the actions from the misuse case were supposed to threaten the objective of the actor, or the action they take to complete their objective?

**Comment by neil-unomaha** [comment]
@ppeters0502 That is a good point.  It isn't really threatening the publish action.  It is threatening the actual modification of the logs.  I'll update it.

**Comment by Emily08** [comment]
> @Emily08
> [Here is what I'm thinking](https://www.lucidchart.com/invitations/accept/8a4af98b-aca3-490d-a449-82ac7ae22337)

I think that makes sense

**Comment by Emily08** [comment]
@neil-unomaha I think that make sense

**Comment by Emily08** [comment]
@ppeters0502 I'm leaning toward the misuse case pointing to modify Orderlog. Is that what you were thinking?

**Comment by ppeters0502** [comment]
> @ppeters0502 I'm leaning toward the misuse case pointing to modify Orderlog. Is that what you were thinking?

Yep! Sorry, I'm behind the times on this one. But yeah, I saw the misuse case threatening modify orderlog!
