### ISSUE TITLE
Develop an outline for this deliverable.

### ISSUE THREAD

**Issue by sanjar91** [sanjar91/Fantastic-Four#6]
I have the following outline for this deliverable in mind, please give us your thoughts:

- Separate the deliverable in 5 sections for 5 use cases. 
- Start with back story, then identify the use case and misusers
- Show the use case diagram including misuse case 
- Type the summary of OSS project documentation for security-related configuration and installation issues.
- Conclude with ending comments and a short summary

**Comment by ppeters0502** [comment]
Like an outline file? (md)

**Comment by sanjar91** [comment]
Yes, but Neil already created the .md file. As discussed earlier we will try to follow the format above for the final deliverable.
