### ISSUE TITLE
Use Case 2 Data Flow

### ISSUE THREAD

**Issue by ppeters0502** [sanjar91/Fantastic-Four#7]
Uses same scenario of delivery management group

**Comment by ppeters0502** [comment]
Pic of data flow
![img_20180923_201658](https://user-images.githubusercontent.com/6621379/45935261-5d285700-bf6f-11e8-9be9-9adc87e12d68.jpg)

**Comment by ppeters0502** [comment]
Actor "Delivery Guy" views active orders by subscribing to Order Log topic. Delivery Guy completes order by publishing to Order Log Topic.
Sound good?

**Comment by Emily08** [comment]
I'll add it to Lucidchart

**Comment by neil-unomaha** [comment]
@ppeters0502  Be sure to include the stereotypes between the misuse cases.  

I think between **monitor rival orders** and **eavesdrop** it should be the "includes" stereotype.  Also: between **eavesdrop** and **view active orders** it should be the "threatens" stereotype.

**Comment by Emily08** [comment]
[Here is the gram for case 2](https://www.lucidchart.com/documents/edit/773e3e5e-9e79-40bc-a1f2-4da73bad809f/0)
